export const FOO_BAR = 'FOO_BAR'

export const CREATE_NEW_POST = 'CREATE_NEW_POST'
export const USER_SIGN_UP    =  'USER_SIGN_UP'
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER'
export const USER_REGISTRATION_SUCCESS  = 'USER_REGISTRATION_SUCCESS'
export const USER_LOG_IN     =  'USER_LOG_IN'
export const FETCH_IMAGE_PREVIEW = 'FETCH_IMAGE_PREVIEW'
